### ISSUE TITLE
Renaming and/or merging of the repository

### ISSUE THREAD

**Issue by 0x2b3bfa0** [helpfulengineering/free-for-covid#1]
This repository was imported from the parallel organization after the renaming and needs to be merged into the new structure.

Given its contents, I would like to convert this repository into an [awesome](https://github.com/sindresorhus/awesome) list called `awesome-covid19` and merge it with one of these while keeping the organization-level control: 

* https://github.com/soroushchehresa/awesome-coronavirus
* <s>https://github.com/adamdriscoll/awesome-covid19-resources</s> (not as good)

**Comment by dmangot** [comment]
We are letting perfect be the enemy of good here.  People need this information yesterday.  This is GitHub, it has revision control.  If you want to publish it like it is now and then change it to another format later, you can do that.  Right now this information is not getting into the hands of the people that need it.

**Comment by 0x2b3bfa0** [comment]
Closing because of its lack of relevance
